services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: pho_similarity
    init: false
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
